pipelines:
  infra-openstack2-images:
    group: openstack
    label_template: "${git[:8]}"
    materials:
      git:
        git: "git@github.com:ai-traders/kolla.git"
        branch: stable/pike
    stages:
      - verify_version:
          clean_workspace: true
          jobs:
            verify_version:
              resources:
                - docker_builder
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks verify_version
      - build:
          clean_workspace: true
          jobs:
            build:
              resources:
                - docker_builder
              tasks:
               - exec:
                  command: /bin/bash
                  arguments:
                    - -c
                    - "./tasks build"
      - release:
          clean_workspace: true
          jobs:
            code:
              resources:
                - docker_builder
              tasks:
                - exec:
                    command: /bin/bash
                    arguments:
                      - -c
                      - ./tasks release
