FROM {{ namespace }}/{{ image_prefix }}base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

{% block ceph_base_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{{ macros.configure_user(name='ceph') }}

{% if base_distro in ['centos', 'oraclelinux', 'rhel'] %}

   {% set ceph_base_packages = [
        'btrfs-progs',
        'ceph',
        'ceph-radosgw',
        'e2fsprogs',
        'hdparm',
        'parted',
        'xfsprogs'
    ] %}

    {% if base_arch in ['aarch64', 'x86_64'] %}
        {% set ceph_base_packages = ceph_base_packages + [
            'ceph-fuse'
        ] %}
    {% endif %}

{% elif base_distro in ['debian', 'ubuntu'] %}

   {% set ceph_base_packages = [
        'btrfs-tools',
        'ceph',
        'e2fsprogs',
        'hdparm',
        'parted',
        'radosgw',
        'xfsprogs',
        'git',
        'python-setuptools',
        'bc'
    ] %}

    {% if base_arch in ['x86_64'] %}
        {% set ceph_base_packages = ceph_base_packages + [
            'ceph-fuse'
        ] %}
    {% endif %}

{% endif %}
{{ macros.install_packages(ceph_base_packages | customizable("packages")) }}

RUN git clone --branch luminous --depth 1 https://github.com/ceph/ceph.git /tmp/ceph &&\
  easy_install /tmp/ceph/src/ceph-volume/ &&\
  rm -rf /tmp/ceph &&\
  ceph-volume -h

RUN sed -i.save -e "s#udev_sync = 1#udev_sync = 0#" -e "s#udev_rules = 1#udev_rules = 0#" -e "s#use_lvmetad = 1#use_lvmetad = 0#" /etc/lvm/lvm.conf

COPY extend_start.sh /usr/local/bin/kolla_extend_start
RUN chmod 755 /usr/local/bin/kolla_extend_start

{% block ceph_base_footer %}{% endblock %}
