FROM {{ namespace }}/{{ image_prefix }}glance-base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

{% block glance_api_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if base_distro in ['centos', 'oraclelinux', 'rhel'] %}
    {% set glance_api_packages = ['qemu-img'] %}
{% elif base_distro in ['debian', 'ubuntu'] %}
RUN apt-get update &&\
 apt-get install -y python-software-properties software-properties-common &&\
 add-apt-repository -y ppa:gluster/glusterfs-3.12
    {% set glance_api_packages = ['qemu-utils', 'glusterfs-client'] %}
{% endif %}

{{ macros.install_packages(glance_api_packages | customizable("packages")) }}

COPY glance_sudoers /etc/sudoers.d/kolla_glance_sudoers
RUN chmod 750 /etc/sudoers.d \
    && chmod 440 /etc/sudoers.d/kolla_glance_sudoers

COPY extend_start.sh /usr/local/bin/kolla_glance_extend_start
RUN chmod 755 /usr/local/bin/kolla_glance_extend_start

{% block glance_api_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER glance
